baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'servicer'
theme = 'hugo-xmin'
googleAnalytics = 'G-2SVCPD0DT1'

[params]
description = 'Simplify Service Management on systemd'
keywords = 'systemd,service,process'

[markup.highlight]
  codeFences = false

[markup.goldmark.renderer]
  unsafe = true
